test fail

diff --git a/.github/workflows/app-stack.yml b/.github/workflows/app-stack.yml
--- a/.github/workflows/app-stack.yml
+++ b/.github/workflows/app-stack.yml
@@ -38,7 +38,8 @@ jobs:
       - uses: actions/checkout@v4
       - name: system test
         run: |
-          echo "System test app"
+          echo "System test app failed"
+          exit 1
   slack:
     name: slack notification
     environment: st-app
